### ISSUE TITLE
Install.sh Assumes Mondoo is installed by Brew if Brew is present on a Mac

### ISSUE THREAD

**Issue by benr** [mondoohq/installer#249]
**Describe the bug**

When running install.sh on a Mac, it looks to see if you have brew installed, if you have mondoo installed and brew installed the upgrade logic assumes it should use brew to upgrade.  There is an edge case possible in which you 1) have brew installed, but 2) install Mondoo via a PKG.  In this case the script fails:

```
* Mondoo Client is already installed. Updating Mondoo...

* Upgrade Mondoo Client via 'brew upgrade'
Error: mondoohq/mondoo/mondoo not installed
The Mondoo Client install script encountered a problem. For assistance, please join our community on GitHub Discussions.
```

Thanks to @misterpantz  for [reporting](https://github.com/orgs/mondoohq/discussions/806) this issue.

**To Reproduce**
1. Install brew
2. Install Mondoo from a PKG (not using brew)
3. Run ```bash -c "$(curl -sSL https://install.mondoo.com/sh)"```
4. It will fail as shown above, attempting a brew upgrade rather than upgrading the PKG.

**Comment by chris-rock** [comment]
With https://github.com/mondoohq/installer/pull/307 users have the option to overwrite the default detection.

```
bash -c "$(cat install.sh)" -- -i pkg
```
