### ISSUE TITLE
Generated systemd service does not work

### ISSUE THREAD

**Issue by imilchev** [mondoohq/installer#279]
**Describe the bug**
I installed cnspec via the command provided in the UI: 
```bash
bash -c "$(curl -sSL https://install.mondoo.com/sh/cnspec)"
```
That creates a systemd service file automatically, which I wanted to use. When I started the service I saw this in `journalctl`:
```
Mar 10 17:34:30 raspberrypi systemd[1]: Started cnspec Service.
Mar 10 17:34:30 raspberrypi systemd[1959147]: cnspec.service: Changing to the requested working directory failed: No such file or directory
Mar 10 17:34:30 raspberrypi systemd[1959147]: cnspec.service: Failed at step CHDIR spawning /usr/bin/cnspec: No such file or directory
Mar 10 17:34:30 raspberrypi systemd[1]: cnspec.service: Main process exited, code=exited, status=200/CHDIR
Mar 10 17:34:30 raspberrypi systemd[1]: cnspec.service: Failed with result 'exit-code'.
```

The service file:
```
[Unit]
Description=cnspec Service
After=network-online.target

[Service]
Type=simple
WorkingDirectory=/etc/opt/mondoo/
ExecStart=/usr/bin/cnspec --config /etc/opt/mondoo/mondoo.yml serve
KillMode=process
Restart=on-failure
RestartSec=90
RestartPreventExitStatus=78

[Install]
WantedBy=multi-user.target
```

The folder `/etc/opt/mondoo` does not exist at all on my machine. The credentials are also not located under `/etc/opt/mondoo/mondoo.yml`. They are in my home directory under `~/.config/mondoo/mondoo.yml`.

**To Reproduce**

1. Run `bash -c "$(curl -sSL https://install.mondoo.com/sh/cnspec)"` on a Linux machine that never had mondoo installed
2. Reload systemd `sudo systemctl daemon-reload`
3. Start the service `sudo systemctl start cnspec`
4. Note the error

**Expected behavior**
The service should start

**Screenshots or CLI Output**
If applicable, add screenshots or the CLI output to help explain your problem.

**Desktop (please complete the following information):**

- OS: Linux raspberrypi 5.15.84-v8+

**Additional context**

**Comment by benr** [comment]
It would generally be considered highly unusual for a daemonized service to read from a home directory.    Presently the script registers and configures for /etc/opt/mondoo.yaml (see https://github.com/mondoohq/installer/blob/main/install.sh#L487) if a registration token is provided (see https://github.com/mondoohq/installer/blob/main/install.sh#L514).

It is assumed that installations of cnquery or cnspec are intended to be non-platform installations and therefore should neither register nor daemonize.

@chris-rock Opinion?

**Comment by imilchev** [comment]
It could be that this just requires docs update. It's just that whatever is written now, gives the impression this should work, but it does not

**Comment by benr** [comment]
@imilchev Please review https://github.com/mondoohq/cnspec/pull/873 and let me know if that solves your underlying concern.  

Closing this issue.
