### ISSUE TITLE
mondoo linux package dependence missing

### ISSUE THREAD

**Issue by atomic111** [mondoohq/installer#291]
i want to install/ update only the mondoo package and then it should download and update the latest cnquery and cnspec package

**Comment by benr** [comment]
@atomic111 This should be supported now.  Which platform did you experience this problem on?

**Comment by atomic111** [comment]
@benr i experienced the problem with SuSe rpm. I think we still have the problem. Maybe I am wrong, but my expectation is if i install cnspec in version 8.3.0 that the rpm requires cnquery in version 8.3.0. Also, if i install the mondoo rpm package in version 8.3.1 that requires installing cnquery and cnspec in version 8.3.1

```bash
ip-172-31-81-84:~ # rpm -qa | grep -E 'mondoo|cnspec|cnquery'
cnquery-8.2.0-1.x86_64
cnspec-8.3.0-1.x86_64
mondoo-8.3.1-1.noarch
```

```bash
ip-172-31-81-84:~ # rpm -qpR mondoo_8.3.1_linux_amd64.rpm
/bin/sh
cnspec
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
```

**Comment by benr** [comment]
https://github.com/mondoohq/installer/blob/main/helper/build_rpms.sh#L36. 

```
benr@swell:~$ docker run -ti registry.suse.com/bci/bci-base:latest bash
Trying to pull registry.suse.com/bci/bci-base:latest...
...
3cf4becf24b1:/ # curl -O https://releases.mondoo.com/mondoo/8.13.0/mondoo_8.13.0_linux_amd64.rpm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6751  100  6751    0     0  16731      0 --:--:-- --:--:-- --:--:-- 16710
3cf4becf24b1:/ # rpm -Uvh mondoo_8.13.0_linux_amd64.rpm
warning: mondoo_8.13.0_linux_amd64.rpm: Header V4 RSA/SHA512 Signature, key ID 00e1c42b: NOKEY
error: Failed dependencies:
	cnspec is needed by mondoo-8.13.0-1.noarch
```

So the dependancy does exist.  

My testing did reveal that we don't play nice with SuSE's yum equiv 'zypper', but thats a separate request.
