### ISSUE TITLE
SHA checksum for cnquery formula missing

### ISSUE THREAD

**Issue by marcelhuth** [mondoohq/installer#350]
**Describe the bug**
When installing or updating cnquery 8.24.4 via Homebrew SHA checksum cannot be validated. A warning is shown. Installation runs without validating the checksum. 

mondoo-homebrew repository shows an empty checksum string here: https://github.com/mondoohq/homebrew-mondoo/blob/860c44d680cd3ddfe9ecce98a48de52f1519a7d8/Formula/cnquery.rb#L12

**To Reproduce**

brew upgrade cnquery 

or

brew install cnquery

**Expected behavior**
cnquery will be installed without a warning. 

**Screenshots or CLI Output**
n/a

**Desktop (please complete the following information):**

- OS: macOS
- OS Version: 14.0

**Additional context**
n/a

**Comment by atomic111** [comment]
@marcelhuth we have fixed it. Can we close it?

**Comment by marcelhuth** [comment]
Hi @atomic111 , sure. Please feel free to close it. I guess it was specific to 8.24.4 release.
