### ISSUE TITLE
Use curl -retry in workflows

### ISSUE THREAD

**Issue by chris-rock** [mondoohq/installer#421]
**What is not working as you expected it?**

Sometimes network connectivity fails. Eg. https://github.com/mondoohq/installer/actions/runs/7637185719. This was caused by a failing curl requests. 

**Expected behavior (i.e. solution)**

We could use curl's retry to make the download more resilient https://everything.curl.dev/usingcurl/downloads/retry. This would also be applicable to other curl commands we use in our workflows.

**Comment by benr** [comment]
I think this is a great idea.  In the case of the job failing today (https://github.com/mondoohq/installer/actions/runs/7629954338) repeated attempts across several hours yielded the same result suggesting it was a problem on the server side that would have timed out any number of retries.  Regardless it's still a wise idea so long as the retry is limited to avoid an excessive run time, such as:

```
curl --retry 10 --retry-delay 60 https://example.com
```
