### ISSUE TITLE
Add `org.opencontainers.image` labels to all images

### ISSUE THREAD

**Issue by tas50** [mondoohq/installer#448]
**Describe the bug**
This is the original metadata used by tooling to trace a container back to its source repo. We should add this to our images in addition to the version fields we're already adding:

- org.opencontainers.image.source
- org.opencontainers.image.vendor
- org.opencontainers.image.licenses
- org.opencontainers.image.url
- org.opencontainers.image.documentation

**Comment by chris-rock** [comment]
Out of curiosity, can you link the specific spec?

**Comment by tas50** [comment]
We can actually skip this now that we're pushing full attestation data
