### ISSUE TITLE
URGENT: Installer 11.28.0 FAILED ON ALL WINDOWS SYSTEMS because of failure in installer!

### ISSUE THREAD

**Issue by danielwillshare** [mondoohq/installer#488]
@atomic111 Please fix asap the following issue.

**Describe the bug**
After cnspec Installation with ansible role 2.4.0 the commanc "cnspec version" is performed, but this command fails with "msg": "Failed to run: 'cnspec version': Could not find specified -WorkingDirectory 'C:\\Program Files\\Mondoo'".

After inspecting this issue, we recognoized that mondoo is not installed anymore in C:\Program Files\Mondoo in 11.28.0. It's now installed in "C:\Program Files (x86)\mondoo"...

![image](https://github.com/user-attachments/assets/fabc6280-f38c-46b3-baf2-4f0608d9ebfb)

... but the Path in the role expects the working directory C:\Program Data\mondoo, so all installations are failed. See...

![image](https://github.com/user-attachments/assets/fda847c2-2935-4122-a28a-29953c5b8893)

... and this is empty now:
![image](https://github.com/user-attachments/assets/0c67c52e-3ccf-49dc-966f-2964eeb5770d)

**To Reproduce**

Install mondoo with ansible role 2.4.0, run cnspec version

**Expected behavior**
Install and cnspec working dir should match.

**Screenshots or CLI Output**
Path variable after Installation:
![image](https://github.com/user-attachments/assets/0e649312-1f9d-4c7c-a346-4753a863e935)
Content of C:\Program Files\mondoo:
![image](https://github.com/user-attachments/assets/85596582-154d-469f-bcfb-c85bb3ffa6b9)
Content of C:\Program Files (x86)\mondoo
![image](https://github.com/user-attachments/assets/6a8b7a49-9059-4cd4-8daa-450c4b1b4a13)

**Desktop (please complete the following information):**

- OS: Windows
- OS Version: all
- Browser if applicable: n/a
- Browser Version: n/a

**Additional context**

As a workaround we have to uninstall the 11.28.0 now manually on all systems and performing emergency changes, because our baslining on all systems and default installation will not work anymore.

Please fix the version as soon as possible.

**Comment by danielwillshare** [comment]
We already have seen the update and currently deploying in productive, after testing in test. Seems to be allright now. I will give you an update if all is working as expected....

**Comment by atomic111** [comment]
Thank you for the info

**Comment by danielwillshare** [comment]
Thanks for the fix in Version 11.28.1. Our productive is in a stable state now and we freezed our environment to this version now. 

Next step is to build up a version control for that. We can discuss some ideas in our next meeting.
